### ISSUE TITLE
questions : why minSdkVersion 23 

### ISSUE THREAD

**Issue by Ali1Ammar** [jonatadashi/youtube_plyr_iframe#11]
hii thanks for this fork it is really awesome but i just notice
in orginal plugin sdk version  20 was supported as it is min sdk support by platform view  and flutter_inappwebview
but in this fork is 23 
is there other factor ( except platform view , flutter_inappwebview ) effect this choice ?

**Comment by jonatadashi** [comment]
You can still use 20. But for me it’s a state of mind, it’s almost a decade old.

See android version market share.
