### ISSUE TITLE
Feature Request - showTopMenu()

### ISSUE THREAD

**Issue by taw1313** [jonatadashi/youtube_plyr_iframe#12]
Due to Youtube's top menu,  the fullscreen controls are hidden under the top menu on some phones ( most IOS )...
If we had a showTopMenu() I could then control the duration the top menu is displayed after transitioning the play state.
Which might help staying within Youtube's TOS.

**Comment by jonatadashi** [comment]
Haven't tested this, but you could try to delay `hidetopmenu()`.

**Comment by taw1313** [comment]
> Haven't tested this, but you could try to delay `hideTopMenu()`.

Thank you for your response.  
I am using a timer to hideTopMenu() and it works to HIDE the top menu. 

hideTopMenu() that woks Example:
```
class ManageTopMenu extends StatelessWidget {
  ManageTopMenu();
  @override
  Widget build(BuildContext context) {
    return YoutubeValueBuilder(
      builder: (context, value) {
        if (value.playerState != PlayerState.playing) {
          Timer(Duration(seconds: 5), () {
            context.ytController.hideTopMenu();
          });
        }
        return Container();
      },
    );
  }
}
```

But after you hide the top menu it is never displayed again for the life of the controller ( until it is destroyed). I need the ability to display or show ( un-hide ) it again during play state transitions for a few seconds and then I can hide the top

What I need to be able to do is something like this...

```
class ManageTopMenu extends StatelessWidget {
  ManageTopMenu();
  @override
  Widget build(BuildContext context) {
    return YoutubeValueBuilder(
      builder: (context, value) {
        if (value.playerState != PlayerState.playing) {
           **context.ytController.showTopMenu();**           
           Timer(Duration(seconds: 5), () {
              context.ytController.hideTopMenu();
           });
        }
        return Container();
      },
    );
  }
}
```

**Comment by jonatadashi** [comment]
Alright, published new version with `showTopMenu()` included.

Could you check if that's what you requested? `youtube_plyr_iframe: ^2.0.1`

**Comment by taw1313** [comment]
> Alright, published new version with `showTopMenu()` included.
> 
> Could you check if that's what you requested? `youtube_plyr_iframe: ^2.0.1`

Quick test on an Android and iOS it worked as expected.  
perfect
thank you!
