### ISSUE TITLE
White padding/line below the youtube player

### ISSUE THREAD

**Issue by engineerdeep** [jonatadashi/youtube_plyr_iframe#18]
**Describe the bug**
The player has a white padding/white line underneath it. It's not visible unless you add a container below it as shown in the screenshot. When the list view containing the video is scrolled the white line flickers alot. 

**To Reproduce:**
Add a video inside a listview, add a container below it.

**Expected behavior:**
There should be no white line/ padding below it.

**Screenshot:**
<img width="385" alt="image" src="https://user-images.githubusercontent.com/38655985/112726620-d5ed3d00-8f37-11eb-9ec8-f03d322cc846.png">

**Comment by jonatadashi** [comment]
Should be fixed now.

Could you please check? `youtube_plyr_iframe: ^2.0.2`

**Comment by engineerdeep** [comment]
Hey, thank you for the prompt response. I tried `2.0.2` but it still has the same issue.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/38655985/112735621-e36deb80-8f66-11eb-8a8e-acfff8a7ed96.png">

Was this line supposed to be the fix for it? 
https://github.com/jonatadashi/youtube_plyr_iframe/blob/eede8c52df7b342e5543577e833d2a1bc2c71fc9/lib/youtube_plyr_iframe.dart#L51

**Comment by jonatadashi** [comment]
The aspectRatio was only for testing purposes, has been reverted.

I've tested on both the simulator and the [web](https://jonatadashi.github.io/Web-Example/#/) and can't seem to reproduce.

Could you paste reproducible code.

**Comment by engineerdeep** [comment]
Oh, I could pretty easily reproduce it.  Using `youtube_plyr_iframe: ^2.0.2`

Here's the code for it - 
```
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String videoID = "sG4cou_LSBo";
  YoutubePlayerController _controller;

  @override
  void dispose() {
    _controller.showTopMenu();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _controller = YoutubePlayerController(
      initialVideoId: videoID,
      params: const YoutubePlayerParams(
        enableCaption: false,
        enableJavaScript: false,
        showControls: true,
        showFullscreenButton: false,
        desktopMode: true,
        playsInline: true,
        showVideoAnnotations: false,
      ),
    );
    return Scaffold(
      appBar: AppBar(
        title: Text('Youtube Sample'),
      ),
      body: Column(
        children: [
          YoutubePlayerIFrame(
            controller: _controller,
            aspectRatio: 16 / 9,
          ),
          Container(
            height: 100.0,
            color: Colors.black,
          ),
        ],
      ),
    );
  }
}
```

<img width="435" alt="image" src="https://user-images.githubusercontent.com/38655985/112757419-c84cbb80-8ffa-11eb-89a9-65b086e4585a.png">

**Comment by jonatadashi** [comment]
Alright, should be fixed now.
Please check: `youtube_plyr_iframe: ^2.0.3-rc.2`

![Simulator Screen Shot - iPhone 12 - 2021-03-28 at 18 40 17](https://user-images.githubusercontent.com/14951074/112760267-8ae62f00-8ff6-11eb-8162-21cf238da1cb.png)

**Comment by engineerdeep** [comment]
Wow, that was such a prompt response! Thank you SO much!

I'm so sorry to nitpick, but there's still a veeeryy slight white line visible, it would be okay if it was there but it still flickers when I scroll so it gets visible. Please check the screenshot below:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/38655985/112764358-2a1c1e00-9019-11eb-84dd-3a65a021a30c.png">

**Comment by engineerdeep** [comment]
Found the issue -
```
Container(
      decoration: BoxDecoration(
        border: Border.all(
            width: 0, color: Colors.black),
        color: Colors.black,
      ),
      child: InAppWebView...
```
