### ISSUE TITLE
Video scrolls with when scrolling down

### ISSUE THREAD

**Issue by sarp86** [jonatadashi/youtube_plyr_iframe#2]
Video hangs on the navigation bar when scrolling and video scrolls with it.

Flutter dev channel  1.26.0-17.2.pre
Tested on iOS iphone 12 simulator & device

**Comment by jonatadashi** [comment]
Please paste example code, as I can't seem to replicate.

**Comment by sarp86** [comment]
> Please paste example code, as I can't seem to replicate.

You can find code in the link:
https://gist.github.com/mkoehne/88ff586425d15e883fa292fb9aa308cb

![Bug_video](https://user-images.githubusercontent.com/44084914/109234402-f062b800-77cb-11eb-89e6-826a40266581.png)

Would nice if you could fix it, thank you

**Comment by jonatadashi** [comment]
> You can find code in the link:
> https://gist.github.com/mkoehne/88ff586425d15e883fa292fb9aa308cb
> 
> Would nice if you could fix it, thank you

If it was only one player that wouldn't be a problem.
You were on the right path, but as https://github.com/sarbagyastha/youtube_player_flutter/issues/289 states:

> But the package will only be optimised to use **single player per page**. It won't support list of player as it's very complex to handle fullscreen switch, with multiple players that too with existing limitations of platform views. The new package should be used for the purpose.

I tried to bypass that restriction the best I could and I'm pretty happy with the result.
You can see the result at **[DEMO](https://web-example.starhelix.space/)** and I have just pushed code upstream, which can be looked at **[EXAMPLE](https://github.com/jonatadashi/youtube_plyr_iframe/blob/develop/example/lib/main.dart)**.

**Comment by sarp86** [comment]
Thank for your effort and fast response!
Unfortunately, we didn't like the solution that another window has to be opened first and then you only get into fullscreen mode in the next step.  Is there a more clever solution than bypassing?
 Is the error possibly in the plugin inappwebview?
