### ISSUE TITLE
[Android] autoPlay:true doesn't work 

### ISSUE THREAD

**Issue by twogood** [jonatadashi/youtube_plyr_iframe#21]
**Describe the bug**
I tried youtube_player_iframe 2.0.0 but it did not work on iOS for me so now I'm trying youtube_plyr_iframe 2.0.3 instead. But first I try in Android and there autoPlay:true works but with youtube_plyr_iframe it does not :)

**To Reproduce:**

Let autoPlay be true. Does not make any difference.

**Expected behavior:**

Autoplay video.

**Flutter Doctor:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Additional context**

I've tried to compare the source codes and the only difference I find is the `allow=` to the `<iframe>` but it includes `autoplay`.

**Comment by jonatadashi** [comment]
> Hello! It doesn't seem like we have quite enough information to send this to  a human yet to help out. We would love if you could provide more details about  your issue by following the template without modifying any of the pre-filled text.
> 

Bad bot

**Comment by jonatadashi** [comment]
> **Describe the bug**
> 
> I tried youtube_player_iframe 2.0.0 but it did not work on iOS for me so now I'm trying youtube_plyr_iframe 2.0.3 instead. But first I try in Android and there autoPlay:true works but with youtube_plyr_iframe it does not :)
> 
> 
> 
> **To Reproduce:**
> 
> Steps to reproduce the behavior:
> 
> 
> 
> Let autoPlay be true. Does not make any difference.
> 
> 
> 
> **Expected behavior:**
> 
> 
> 
> Autoplay video.
> 
> 
> 
> **Flutter Doctor:**
> 
> 
> 
> Doctor summary (to see all details, run flutter doctor -v):
> 
> [✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> 
>     ✗ Android license status unknown.
> 
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
> 
>       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
> 
> [✓] Chrome - develop for the web
> 
> [✓] Linux toolchain - develop for Linux desktop
> 
> [✓] Android Studio (version 4.1)
> 
> [✓] Android Studio
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
> 
> [✓] Connected device (3 available)
> 
> 
> 
> ! Doctor found issues in 1 category.
> 
> 
> 
> 
> 
> 
> 
> **Additional context**
> 
> 
> 
> I've tried to compare the source codes and the only difference I find is the `allow=` to the `<iframe>` but it includes `autoplay`. 
> 
> 

I'll look into it.

**Comment by jonatadashi** [comment]
Thanks for reporting. I'll look into it.

**Comment by twogood** [comment]
> Thanks for reporting. I'll look into it.

Thanks! I have invited you to a repo called "ddf" with two branches: the main branch has youtube_player_iframe (autoPlay works) and then there is another branch called use-youtube_plyr_iframe (autoPlay does not work). I've even tried to restore the  `useShouldOverrideUrlLoading` changes that you have removed but it didn't seem to help either. There is not so much else that differs so I'm starting to wonder if it is a timing issue somehow.

**Comment by jonatadashi** [comment]
> > Thanks for reporting. I'll look into it.
> 
> Thanks! I have invited you to a repo called "ddf" with two branches: the main branch has youtube_player_iframe (autoPlay works) and then there is another branch called use-youtube_plyr_iframe (autoPlay does not work). I've even tried to restore the `useShouldOverrideUrlLoading` changes that you have removed but it didn't seem to help either. There is not so much else that differs so I'm starting to wonder if it is a timing issue somehow. I've only tried Android at the moment. On web, autoPlay is not supported by the browsers anyway.

I've tested it on youtube_player_iframe and it doesn't seem to be working there too.


You'll have to either run in `desktopMode: true` or add `play()` to the controller.
See [example](https://github.com/jonatadashi/youtube_plyr_iframe/blob/6bb98dc93c10fa952952d9efbd5c65e5e61f1af3/example/lib/main.dart#L246) for more details.

**Comment by twogood** [comment]
Thanks a bunch, I'll call play myself then!
