### ISSUE TITLE
Video sometimes plays in desktop mode.

### ISSUE THREAD

**Issue by tuanbs** [jonatadashi/youtube_plyr_iframe#40]
Hello Sir, I notice that sometimes the video plays in desktop mode even though its default value is false. Please suggest any idea or workaround to fix this issue. Thanks in advance.

**Comment by jonafeucht** [comment]
Hi, what device and version are you testing on?
Possibly post flutter doctor -v

**Comment by tuanbs** [comment]
> Hi, what device and version are you testing on?
> Possibly post flutter doctor -v

Hi, I'm testing on iPhone 7 with latest version of both iOS and Flutter. The problem here is that sometimes it plays in Desktop mode and sometimes not, even though I set the Desktop mode flag to false. I got the same problem when I tried `youtube_player_iframe` package.
