### ISSUE TITLE
No Audio button on Web (Safari and Chrome)

### ISSUE THREAD

**Issue by Felipebb** [jonatadashi/youtube_plyr_iframe#41]
The audio button doesn't appear in the web version of my app, when used in mobile browsers

![image](https://user-images.githubusercontent.com/50642879/133479065-1c4267b1-be47-45b7-9b11-570ec7043da4.png)
```
YoutubePlayerController(
      initialVideoId: widget.tutorialVideoArgs!.url!,
      params: YoutubePlayerParams(
          showControls: true,
          autoPlay: true,
          showFullscreenButton: true,
          mute: true,
          desktopMode: true,
          enableCaption: true,
          enableJavaScript: true,
));

**Comment by jonafeucht** [comment]
Hi, this is a limitation with smaller screens, nothing I can do.

**Comment by Felipebb** [comment]
The app and the web version were tested with the same screen size, but only in the app the button appears, screen limitation?
