### ISSUE TITLE
youtube_plyr_iframe player running in emulator but keep getting crashed the app on real android device.

### ISSUE THREAD

**Issue by rajmouryapi** [jonatadashi/youtube_plyr_iframe#8]
#51 pc 0000000000003680  /system/bin/app_process64 (main+1592) (BuildId: 4076a8a516172b5372277069ce0546fd)
      #52 pc 000000000008506c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: a790cdbd8e44ea8a90802da343cb82ce)
Lost connection to device.
Exited (sigterm)

kindly look into the issue.

**Comment by jonatadashi** [comment]
Please download and run [EXAMPLE](https://github.com/jonatadashi/youtube_plyr_iframe/blob/develop/example/lib/main.dart) independently and let me know if it's still acting up.

Which version of youtube_plyr_iframe are you using?
I'm pretty confident that it's another package acting up or package incompatibility.

Please also paste full `error terminal output` and `flutter doctor -v`.
